name = "appimprovegeneratorapp202012326cb7bdde2e44"
bin = "bin/appimprovegeneratorapp202012326cb7bdde2e44"
vcs = "git"
with_pop = true
with_sqlite = false
with_dep = false
with_webpack = false
with_nodejs = false
with_yarn = false
with_docker = true
with_grifts = true
as_web = false
as_api = true
