package actions

import (

  "fmt"
  "github.com/gobuffalo/buffalo"
  "github.com/gobuffalo/pop"
  "generatedApps/appimprovegeneratorapp202012326cb7bdde2e44/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Interview)
// DB Table: Plural (interviews)
// Resource: Plural (Interviews)
// Path: Plural (/interviews)
// View Template Folder: Plural (/templates/interviews/)

// InterviewsResource is the resource for the Interview model
type InterviewsResource struct{
  buffalo.Resource
}

// List gets all Interviews. This function is mapped to the path
// GET /interviews
func (v InterviewsResource) List(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  interviews := &models.Interviews{}

  // Paginate results. Params "page" and "per_page" control pagination.
  // Default values are "page=1" and "per_page=20".
  q := tx.PaginateFromParams(c.Params())

  // Retrieve all Interviews from the DB
  if err := q.All(interviews); err != nil {
    return err
  }

  // Add the paginator to the context so it can be used in the template.
  c.Set("pagination", q.Paginator)

  return c.Render(200, r.Auto(c, interviews))
}

// Show gets the data for one Interview. This function is mapped to
// the path GET /interviews/{interview_id}
func (v InterviewsResource) Show(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Interview
  interview := &models.Interview{}

  // To find the Interview the parameter interview_id is used.
  if err := tx.Find(interview, c.Param("interview_id")); err != nil {
    return c.Error(404, err)
  }

  return c.Render(200, r.Auto(c, interview))
}

// Create adds a Interview to the DB. This function is mapped to the
// path POST /interviews
func (v InterviewsResource) Create(c buffalo.Context) error {
  // Allocate an empty Interview
  interview := &models.Interview{}

  // Bind interview to the html form elements
  if err := c.Bind(interview); err != nil {
    return err
  }

  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Validate the data from the html form
  verrs, err := tx.ValidateAndCreate(interview)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    // Make the errors available inside the html template
    c.Set("errors", verrs)

    // Render again the new.html template that the user can
    // correct the input.
    return c.Render(422, r.Auto(c, interview))
  }

  // and redirect to the interviews index page
  return c.Render(201, r.Auto(c, interview))
}

// Update changes a Interview in the DB. This function is mapped to
// the path PUT /interviews/{interview_id}
func (v InterviewsResource) Update(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Interview
  interview := &models.Interview{}

  if err := tx.Find(interview, c.Param("interview_id")); err != nil {
    return c.Error(404, err)
  }

  // Bind Interview to the html form elements
  if err := c.Bind(interview); err != nil {
    return err
  }

  verrs, err := tx.ValidateAndUpdate(interview)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    // Make the errors available inside the html template
    c.Set("errors", verrs)

    // Render again the edit.html template that the user can
    // correct the input.
    return c.Render(422, r.Auto(c, interview))
  }

  // and redirect to the interviews index page
  return c.Render(200, r.Auto(c, interview))
}

// Destroy deletes a Interview from the DB. This function is mapped
// to the path DELETE /interviews/{interview_id}
func (v InterviewsResource) Destroy(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Interview
  interview := &models.Interview{}

  // To find the Interview the parameter interview_id is used.
  if err := tx.Find(interview, c.Param("interview_id")); err != nil {
    return c.Error(404, err)
  }

  if err := tx.Destroy(interview); err != nil {
    return err
  }

  // Redirect to the interviews index page
  return c.Render(200, r.Auto(c, interview))
}
